spring.application.name=task-manager

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://task_manager_lz16_user:EAFR0vH7rbWCNJ6kvVpIBCLgByT1yPKy@dpg-d7fptvq8qa3s738blmh0-a.oregon-postgres.render.com/task_manager_lz16}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Tamilraj190607@}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Server Port
server.port=${PORT:8080}
