spring.application.name=task-manager

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-round-art-apmbfzfd.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GlS0vqNW8hfj
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Server Port
server.port=${PORT:8080}
